export const
SET_MIN_PRICES = 'SET_MIN_PRICES',
SET_URLS = 'SET_URLS',
SHOW_PRICE_HISTORY = 'SHOW_PRICE_HISTORY',
SET_DAYILY_PRICES = 'SET_DAYILY_PRICES',
SET_PAGINATION_PAGE = 'SET_PAGINATION_PAGE',
SET_ITEMS_KOL = 'SET_ITEMS_KOL',
SET_DATE_FROM = 'SET_DATE_FROM',
SET_DATE_TO = 'SET_DATE_TO',
SET_LAST_UPDATE_DATE = 'SET_LAST_UPDATE_DATE',
UPDATE_PRICES = 'UPDATE_PRICES',
UPDATE_URLS = 'UPDATE_URLS',
SET_URLS_COUNT = 'SET_URLS_COUNT',
SET_URLS_ACTIVE = 'SET_URLS_ACTIVE'